# Generated by Django 5.0.3 on 2024-03-20 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('profile_date', models.DateTimeField(default=datetime.datetime.now)),
                ('security', models.ImageField(upload_to='')),
                ('passbook', models.ImageField(upload_to='')),
                ('Aadhar', models.ImageField(upload_to='')),
                ('date_issued', models.DateTimeField(default=datetime.datetime.now)),
                ('amount_issued', models.IntegerField()),
                ('amound_paid', models.IntegerField()),
                ('logs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
