# Generated by Django 5.0.3 on 2024-03-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byaaj', '0004_customer_amound_paid_customer_profile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
