# Generated by Django 5.0.3 on 2024-03-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byaaj', '0006_owner_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100, null=True),
        ),
    ]
