# Generated by Django 5.0.3 on 2024-03-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byaaj', '0010_rename_password_customer_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password2',
        ),
        migrations.AddField(
            model_name='user1',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='user1',
            name='user_email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
    ]
