# Generated by Django 5.0.3 on 2024-03-21 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byaaj', '0014_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='is_owner',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default='is_customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
