# Generated by Django 5.0.3 on 2024-03-21 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byaaj', '0016_alter_status_groups_alter_status_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Is_customer'),
        ),
    ]
