# Generated by Django 5.0.3 on 2024-03-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byaaj', '0017_alter_customer_user_alter_status_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
