# Generated by Django 5.0.3 on 2024-06-10 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byaaj', '0021_remove_customer_duration_customer_loan_for_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='loan_for_months',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Months'),
        ),
    ]
